version: '2'

networks:
  myconnect:
    driver: bridge
services:
  application:
    image: euclid1990/ubuntu-server
    volumes:
      - ./backend:/var/www/html/backend
    networks:
      - myconnect
  monolith-postgres:
    container_name: c-postgres
    image: postgres:13.1
    ports:
      - 5433:5432
    volumes:
      - /monolith/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - myconnect
  php:
    image: php:7.4-fpm
    ports:
      - "9696:9000"
    volumes_from:
      - application
    links:
      - monolith-postgres:pgsql
    networks:
      - myconnect
  nuxt:
    build:
       dockerfile: Dockerfile
       context: ./nuxtjs-tutorial
    container_name: nuxt
    ports:
        - "3000:3000"
    networks:
      - myconnect
  nginx:
    image: nginx
    ports:
      - "8696:80"
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx_conf:/etc/nginx/conf.d
    networks:
      - myconnect